name: Complex

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
	steps:
	- run: !
	    echo Ubuntu
	    date

  windows:

    runs-on: windows-latest
	steps:
	- run: !
	    echo Windows
	    date
	
	
  macos:
    runs-on: macos-latest
	steps:
	- run: !
	    echo MacOS
	    date
	
  depends:
    needs: [ubuntu, windows, macos]
	runs-on: 
	steps:
	- run: echo Hello Everyone!	

