name: Complex
on:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu Check
    runs-on: ubuntu-latest
    steps:
      - name: Say Ubuntu
      - run: echo Ubuntu
      - run: date

  windows:
    name: Windows Check
    runs-on: windows-latest
    steps:
      - name: Say Windows
        run: date

  macos:
    name: MacOS Check
    runs-on: macos-latest
    steps:
      - name: Say MacOS
        run: date
